# Generated by Django 2.0.2 on 2021-04-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_shift_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='user',
            new_name='client',
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift',
            field=models.CharField(choices=[('morning shift', 'Morning Shift')], max_length=255),
        ),
    ]
